name: Create PR Develop to Base Branches

on:
  pull_request:
    types: [closed]
    branches:
      - develop
      
permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr-to-base-branches:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Create PR to base/* branches
        uses: actions/github-script@v7
        with:
          script: |
            // Get the list of base/* branches
            const baseBranches = await github.paginate(
              github.rest.repos.listBranches,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
              }
            );

            const baseBranchNames = baseBranches
              .filter(branch => branch.name.startsWith('base/'))
              .map(branch => branch.name);

            if (baseBranchNames.length === 0) {
              console.log('No base/* branches found.');
            }

            // Create PRs for each base/* branch
            for (const baseBranch of baseBranchNames) {
              // Check if a PR already exists for this base branch and develop
              const existingPrs = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                base: baseBranch,
                head: 'develop',
              });

              // If PR already exists, skip creating a new one
              if (existingPrs.data.length > 0) {
                console.log(`PR already exists for base branch ${baseBranch}`);
                continue;
              }

              // Create a new PR if no existing PR is found
              await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `Auto merge develop into ${baseBranch}`,
                body: `This PR is automatically created to merge develop into ${baseBranch}`,
                base: baseBranch,
                head: 'develop',
              });
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
