name: Merge and Create GitHub Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'タグ名（例: 「1.0.0」）'
        required: true
        type: string
      overview:
        desctiption: '概要'
        required: true
        type: string
      backlog_url:
        description: 'BacklogタスクのURL'
        required: false
        type: string
        
permissions:
  contents: write

jobs:
  merge_to_main:
    runs-on: ubuntu-latest
    if: github.actor == 'masayasu-mori-hitowa'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Create Pull Request
        uses: actions/github-script@v7
        id: create-to-main-pr
        with:
          github-token: ${{ secrets.RELEASE_MERGE_TOKEN }}
          script: |
            const releaseTitle = '${{ github.event.inputs.tag_name }}';
            const response = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `リリース v${releaseTitle}`,
              head: 'stage', 
              base: 'main',
              body: '',
            });

            const prNumber = response.data.number;
            console.log('Pull Request created:', response.data.html_url);

            return prNumber;

      - name: Merge Pull Request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.RELEASE_MERGE_TOKEN }}
          script: |
            const prNumber = ${{ steps.create-to-main-pr.outputs.result }};
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const response = await github.rest.pulls.merge({
              owner,
              repo,
              pull_number: prNumber,
              commit_title: `Merge PR ${prNumber}`,
              merge_method: 'merge', 
            });

            console.log('Pull Request merged:', response.data);

  merge_to_develop:
    runs-on: ubuntu-latest
    if: github.actor == 'masayasu-mori-hitowa'
    needs: merge_to_main
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Create Pull Request
        uses: actions/github-script@v7
        id: create-to-develop-pr
        with:
          github-token: ${{ secrets.RELEASE_MERGE_TOKEN }}
          script: |
            const releaseTitle = '${{ github.event.inputs.tag_name }}';
            const response = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `リリース v${releaseTitle}`,
              head: 'main',
              base: 'develop', 
              body: '',
            });

            const prNumber = response.data.number;
            console.log('Pull Request created:', response.data.html_url);

            return prNumber; 

      - name: Merge Pull Request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.RELEASE_MERGE_TOKEN }}
          script: |
            const prNumber = ${{ steps.create-to-develop-pr.outputs.result }}; 
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const response = await github.rest.pulls.merge({
              owner,
              repo,
              pull_number: prNumber,
              commit_title: `Merge PR ${prNumber}`,
              merge_method: 'merge', 
            });

            console.log('Pull Request merged:', response.data);

  create_tag_and_release:
    runs-on: ubuntu-latest
    if: github.actor == 'masayasu-mori-hitowa'
    needs: merge_to_develop
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            ref: 'main'

      - name: Create a tag for main
        run: |
          VERSION_TAG="${{ github.event.inputs.tag_name }}"
          git tag $VERSION_TAG
          git push origin $VERSION_TAG

      - name: Create GitHub Release using action-gh-release
        uses: softprops/action-gh-release@v2
        with:
            tag_name: "${{ github.event.inputs.tag_name }}"
            name: "${{ github.event.inputs.tag_name }}"
            body: |
                # 概要
                ${{ github.event.inputs.overview }}

                # Backlog
                [${{ github.event.inputs.backlog_url }}](${{ github.event.inputs.backlog_url }})
            generate_release_notes: true
            draft: false
            prerelease: false
            make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

