name: Merge and Create GitHub Release

on:
  workflow_dispatch:
    inputs:
      release_title:
        description: 'GitHub Release Title'
        required: true
        type: string
permissions:
  pull-requests: write # PR を作成・マージするための権限
  actions: write   # GitHub Actions の権限
  contents: write    # リポジトリの管理権限（タグ作成、リリース作成）

jobs:
  merge_to_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          curl -fsSL https://github.com/cli/cli/releases/download/v2.7.0/gh_2.7.0_linux_amd64.deb -o gh.deb
          sudo dpkg -i gh.deb

      - name: Ensure branch `stage` exists
        run: git fetch origin stage

      - name: Create Pull Request from `stage` to `main`
        id: pr_create_main
        uses: peter-evans/create-pull-request@v4
        with:
          title: 'Merge stage to main'
          body: 'Automated pull request to merge `stage` into `main`.'
          base: main
          head: stage
          commit-message: 'Merging stage into main'
          labels: 'auto-merge'

      - name: Check for merge conflicts in PR to main
        if: steps.pr_create_main.outputs.pull-request-url != ''
        run: |
          pr_url="${{ steps.pr_create_main.outputs.pull-request-url }}"
          pr_number=$(echo $pr_url | sed 's/.*\/\([0-9]*\)$/\1/')
          pr_status=$(gh pr view $pr_number --json mergeable --jq .mergeable)

          if [ "$pr_status" == "MERGEABLE" ]; then
            echo "No conflicts, merging the PR to main."
            gh pr merge $pr_number --merge --auto --delete-branch
          else
            echo "Conflicts detected, skipping the merge."
            exit 1
          fi

  merge_to_develop:
    runs-on: ubuntu-latest
    needs: merge_to_main
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ensure branch `main` exists
        run: git fetch origin main

      - name: Create Pull Request from `main` to `develop`
        id: pr_create_develop
        uses: peter-evans/create-pull-request@v4
        with:
          title: 'Merge main to develop'
          body: 'Automated pull request to merge `main` into `develop`.'
          base: develop
          head: main
          commit-message: 'Merging main into develop'
          labels: 'auto-merge'

      - name: Check for merge conflicts in PR to develop
        if: steps.pr_create_develop.outputs.pull-request-url != ''
        run: |
          pr_url="${{ steps.pr_create_develop.outputs.pull-request-url }}"
          pr_number=$(echo $pr_url | sed 's/.*\/\([0-9]*\)$/\1/')
          pr_status=$(gh pr view $pr_number --json mergeable --jq .mergeable)

          if [ "$pr_status" == "MERGEABLE" ]; then
            echo "No conflicts, merging the PR to develop."
            gh pr merge $pr_number --merge --auto --delete-branch
          else
            echo "Conflicts detected, skipping the merge."
            exit 1
          fi

  create_tag_and_release:
    runs-on: ubuntu-latest
    needs: merge_to_develop
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate release notes
        run: |
          # Generate release notes based on the differences between main and develop
          git log --oneline $(git merge-base main develop)..develop > release-notes.md

      - name: Create a tag for main
        run: |
          VERSION_TAG="v$(date +'%Y%m%d%H%M%S')"
          git tag $VERSION_TAG
          git push origin $VERSION_TAG

      - name: Create GitHub Release using action-gh-release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release-notes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add release title and finalize GitHub Release
        run: |
          RELEASE_TITLE="${{ github.event.inputs.release_title }}"
          gh release create $VERSION_TAG --title "$RELEASE_TITLE" --notes "$(cat release-notes.md)" $VERSION_TAG
